### ISSUE TITLE
Update your code

### ISSUE THREAD

**Issue by Stepandanci** [vadim030303/Test-Task#1]
Hello,

You wrote a good test task!

Make your changes in another branch (example: `dev`) and open a new pull request to `master` branch.  

I need to check parsing result from demo bank.
Save JSON data with parsed accounts and transactions in a file.

You should write a test that checks the data from demo provider bendigo bank.

1. Read about Rspec. It is a framework for test your code.

- https://rspec.info
- https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers

2. Create `bendigobank_spec.rb` file, describe class BendigoBank.

3. Write specs for `parse_accounts` and `parse_transactions`.

4. Take HTML from bendigo bank and save it in a file (check screenshot).
`html_example = Nokogiri::HTML(File.read('accounts.html'))`

![Снимок](https://user-images.githubusercontent.com/29861352/84526427-f2d8bc80-ace5-11ea-81e2-b36cf686705d.PNG)

5. Call method for parse accounts and send HTML data. `parse_accounts(html_example)`

6. Check the number of accounts and show an example account in a hash format.

Example:
```ruby
it 'check number of accounts and show an example account' do
  html_example = Nokogiri::HTML(File.read('accounts.html'))
  accounts = parse_accounts(html_example) # NOTE: It is my example, not a real code.

  expect(accounts.count).to eq(5)
  expect(accounts.first.to_hash).to eq(
    {
      "name"         => "Demo Everyday Account",
      "currency"     => "USD",
      "balance"      => 1959.90,
      "nature"       => "account",
      "transactions" => []
    }
  )
end
```

7. Do the same for transactions.

Good luck!

**Comment by vadim030303** [comment]
@Stepandanci I have created pull request, please review it.

**Comment by Stepandanci** [comment]
Looks very good! 
Your task is complete. 

I will ask other developers to review it. 
Add folder `/bin` to `.gitignore`.
